/*
 * Created by Asad on 30 May 2023 []
 */

export const colorPallet = {
    colorGrayscaleGray: '#8c8d93',
    colorGrayscaleBlack: '#373946',
    colorGrayscaleBlackWithAlpha: 'rgba(55, 57, 70, 0.5)',
    colorStatusSuccess: '#27d88b',
    colorBrandOrange: '#e75e40',
    colorBrandOrangeLight: 'rgba(255, 180, 114, 1.0)',
    colorBrandNavy: '#2a2961',
    colorBrandNavy3: '#f4f4ff',
    colorGrayscaleWhite: '#ffffff',
    colorGrayscaleWhiteWithAlpha: 'rgba(255, 255, 255, 0.5)',
    colorBrandOrange3: '#ffefec',
    colorGrayscaleLightGray: '#dadbe0',
    colorBrandPink: '#ff81da',
    colorStatusError: '#d82727',
    colorBrandGreen: '#4be7b4',
    colorBrandPurple: '#9045d1',
    colorOverlayBlack: 'rgba(55, 57, 70, 0.7)',
    colorBrandBlue: '#3c89ff',
    colorStatusPending: '#ffa429',
    colorGrayscaleSubtleGray: '#f2f2f2',
    colorcolorGrayscaleBlackWithAlpha2: 'rgba(55, 57, 70, 0.08)',
    colorShadow: 'rgba(0, 0, 0, 0.1)',
    colorlightGray: '#C4C4C4',
    searchBarBorderColor: '#DADBE0',
};

const colors = {
    colorRed: '#FF0000',
    colorWhite: '#FFFFFF',
    lightShadow: `rgba(42, 41, 97, 0.08)`,
    darkshadow: '#142A2961',
    colorGray: colorPallet.colorGrayscaleGray,
    colorBrandOrange3: colorPallet.colorBrandOrange3,
    transparentColor: '#00000000',
    primary: colorPallet.colorBrandOrange,
    tabActiveTintColor: colorPallet.colorGrayscaleBlack,
    tabInActiveTintColor: colorPallet.colorGrayscaleBlackWithAlpha,
    storeCategoryTabIndicatorColor: colorPallet.colorBrandOrange,
    textFieldPlaceHolderColor: colorPallet.colorGrayscaleBlackWithAlpha,
    textFieldTextColor: colorPallet.colorGrayscaleBlack,
    textFieldCursorColor: colorPallet.colorBrandOrange,
    textFieldTitleColor: colorPallet.colorGrayscaleBlack,
    textFieldTitleFocusColor: colorPallet.colorBrandOrange,
    texFieldBottomLineNormalColor: colorPallet.colorBrandNavy,
    gradientButtonTitleColor: colorPallet.colorGrayscaleWhite,
    gradientButtonColors: ['#E75E40', '#E75E40'],
    gradientLoginColors: ['#753A88', '#CC2B5E'],
    gradientFlipButtonColors: ['#FFFFFF', '#FFFFFF'],
    buttonColor: colorPallet.colorBrandOrange,
    gradientButtonDisableColors: [
        colorPallet.colorGrayscaleLightGray,
        colorPallet.colorGrayscaleLightGray,
    ],

    buttonDisableColor: colorPallet.colorGrayscaleLightGray,
    gradientButtonErrorColors: [
        colorPallet.colorStatusError,
        colorPallet.colorStatusError,
    ],
    colorBrandBlue: colorPallet.colorBrandBlue,
    gradientColoryBrandNavy: [
        colorPallet.colorBrandNavy,
        colorPallet.colorBrandNavy,
    ],
    colorBrandNavy: colorPallet.colorBrandNavy,
    gradientHomeColors: [colorPallet.colorBrandNavy, 'rgb(50, 25, 133)'],
    gradientGreenBand: ['rgb(38, 173, 128)', 'rgb(103, 255, 222)'],
    gradientImageOverlayColors: ['rgba(55, 57, 70, 0.0)', 'rgb(55, 57, 70)'],
    gradientStoreImageOverlayColors: [
        'rgba(55, 57, 70, 1.0)',
        'rgba(55, 57, 70, 0.0)',
    ],
    resetPasswordColor: colorPallet.colorBrandOrange,
    separatorColor: colorPallet.colorGrayscaleSubtleGray,
    separatorColorOrange: colorPallet.colorBrandOrange,
    screenBackground: colorPallet.colorGrayscaleWhite,
    otpBoxBorderColor: colorPallet.colorBrandOrange,
    otpBoxTextColor: colorPallet.colorGrayscaleBlack,
    otpCountdownColor: colorPallet.colorGrayscaleBlack,
    searchBarBackground: colorPallet.colorGrayscaleSubtleGray,
    userWidgetBackground: colorPallet.colorGrayscaleWhite,
    shadowColor: colorPallet.colorGrayscaleBlack,
    shadowColor2: colorPallet.colorShadow,
    shadowColor3: colorPallet.colorcolorGrayscaleBlackWithAlpha2,
    lightShadowColor: 'rgb(127, 127, 127)',
    tickColor: colorPallet.colorBrandOrange,
    colorlightGray: colorPallet.colorlightGray,
    gradientOnProgressBarColors: [
        colorPallet.colorBrandNavy,
        colorPallet.colorlightGray,
    ],
    gradientOnCompleteGrayBarColors: [
        colorPallet.colorlightGray,
        colorPallet.colorlightGray,
    ],
    gradientAccountColors: [colorPallet.colorBrandNavy, 'rgb(50, 25, 133)'],
    gradientEarchCashColors: [
        colorPallet.colorBrandPurple,
        'rgb(220, 157, 255)',
    ],
    gradientWithdrawColors: [colorPallet.colorBrandBlue, 'rgb(103, 239, 237)'],
    gradientReferColors: [colorPallet.colorBrandNavy, 'rgb(50, 25, 133)'],
    gradientAutomaticWalletColors: [
        colorPallet.colorBrandNavy,
        'rgb(50, 25, 133)',
    ],
    toolbarIconsTint: colorPallet.colorBrandNavy,
    appleButtonBackgroundColor: colorPallet.colorGrayscaleBlack,
    socialLoginButtonBackgroundColor:
        colorPallet.colorcolorGrayscaleBlackWithAlpha2,
    progressBarBgColor: colorPallet.colorBrandOrange3,
    searchDealsBgColor: colorPallet.colorBrandOrange3,
    progressBarProgressColor: colorPallet.colorBrandOrange,
    withdrawalTitleBackgroundColor: colorPallet.colorStatusPending,
    cashbackApprove: colorPallet.colorStatusSuccess,
    cashbackpending: colorPallet.colorStatusPending,
    cashbackreject: colorPallet.colorStatusError,
    errorTextColor: colorPallet.colorStatusError,
    balanceInfoGreyBg: colorPallet.colorGrayscaleSubtleGray,
    walletArrowBtn: colorPallet.colorGrayscaleBlack,
    storeListGreyBackground: colorPallet.colorBrandNavy3,
    searchBarBorderColor: colorPallet.searchBarBorderColor,
};

export default colors;
